server:
  port: 9092

jux:
  base-package: xss.it.jux.clientdemo.pages
  ssr:
    cache:
      enabled: false
  a11y:
    enabled: true
    audit-on-render: true
    fail-on-error: false
    log-violations: true
    default-lang: en
  i18n:
    enabled: true
    default-locale: en
    locales:
      - en
    base-name: lang

spring:
  main:
    banner-mode: off
